<% require 'tmpdir' %>
---
driver: lxd

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

transport: lxd

verifier: inspec

suites:
  - name: kitchen-lxd-native
    provisioner:
      downloads:
        '/tmp/kitchen': <%= Dir.tmpdir %>/kitchen-download-test
    verifier:
      inspec_tests:
        - name: default
  - name: kitchen-lxd-cloud
    driver:
      image_server: https://cloud-images.ubuntu.com/releases
      username: ubuntu
    verifier:
      inspec_tests:
        - name: default