<% require 'tmpdir' %>
---
driver: lxd

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.0.202

platforms:
  - name: ubuntu-18.04
    
suites:
  - name: kitchen-lxd-native
    verifier: inspec
    provisioner:
      downloads:
        '/tmp/kitchen': <%= Dir.tmpdir %>/kitchen-download-test
  - name: kitchen-lxd-cloud
    driver:
      image_server: https://cloud-images.ubuntu.com/daily
      ssh_login: ubuntu
