<% require 'tmpdir' %>
---
driver: lxd

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

transport: lxd

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

suites:
  - name: kitchen-lxd-native
    provisioner:
      downloads:
        '/tmp/kitchen': <%= Dir.tmpdir %>/kitchen-download-test
  - name: kitchen-lxd-cloud
    driver:
      image_server: https://cloud-images.ubuntu.com/releases
      username: ubuntu
