---
driver:
  name:  lxd

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
      image_server: https://cloud-images.ubuntu.com/releases

suites:
  - name: default
    run_list:
    attributes:
