sudo: required
language: ruby
rvm:
- 2.4.3
- 2.5.0
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
script:
- rake --tasks
- bundle exec kitchen diagnose
- echo $BUNDLE_GEMFILE
- env -i KITCHEN_YAML=.kitchen.travis.yml PATH="$PATH" kitchen converge travis
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
- sudo su -l $USER -c "cd $(pwd) && rvm use ${RUBY_VERSION/ruby-/} && rake kitchen:all"
deploy:
  provider: rubygems
  api_key:
    secure: A599p8PjugFfsTdWLLHW1Rl2yaMLWfFpUAV1Oq4qFG2RqMQXgM4zWGO4+Upff6zJ07qxOqon0kjysaU46Pwollp4pS+5sogtFPkcboSi8qhjeCJ3eYo6O1GWLD+5kBZ1PIS9iRPqTGKFPB677KmjXEdmdYvBY4x01tOK23KzjsjtdXO3/6C8BD7pg5EC2qGxjztkbzGm8OZXbGvTvQ5lxtQe5H4ldHr6zs6ZUu/OzszGofXwWMRxeOu0UHkcrHrDUJ/HIJxjm7ogOQI7C016KksCPcYCG3GeS/Od/tVMZiQ0Z2LVV0dQjLTFzD9fGqIcGTur1M+pE4lv4NMFHZc6ICVJgVEegQ8S0SVbkpXijrw4ahahfRTU8U//hmnR4wnRAEd2N5IYA4ChQqwUcARBnmVb/uxQASEvF4tLBzjvUdgUMggWr94705ATIOqIu2CsQZYxGU5nsD3WxYBRM1ByVFq+yT93OsBmhAMwwurhVwP0yjL5Fi8ax94Guq8JD7BnbhON3nEwevLI5/O14bNhdHmb9O7sjQ5qdmqStmxIB96wLADuLUYFhPCh+zLIYzGulcHRId7QyqavU9seSIg+XL8dbM0Iljfi//lrq9FDEyYlh35nSf+p0UnNLfC10qXnBp8ojb/GhEXOyqIEDWmKO/Ose1OJ5Cr4qtN7Ye0+B7s=
  gem: kitchen-lxd_sling
  on:
    tags: true
    rvm: 2.4.3
  