sudo: required
language: ruby
env:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
rvm:
  - 2.4.2
  - ruby-head
script:
  - rake --tasks
  - kitchen diagnose
  - rake kitchen:travis-local
  - sudo su -l $USER -c "rake kitchen:test-ubuntu-1604"
