sudo: false
language: ruby
env:
  - KITCHEN_LOCAL_YAML='.kitchen.travis.yml'
rvm:
  - 2.4.2
  - ruby-head
script:
  - rake --tasks
  - kitchen diagnose
  - rake kitchen:travis-local
  - rake kitchen:test-ubuntu-1604
