sudo: required
language: ruby
env:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
rvm:
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
script:
  - rake --tasks
  - bundle exec kitchen diagnose
  - rake kitchen:travis-local
  - sudo su -l $USER -c "cd $(pwd) && rvm use ${RUBY_VERSION/ruby-/} && rake kitchen:test-ubuntu-1604"
